//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPN
    {
        public string MAHDNHAP { get; set; }
        public string MASP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual NHAPKHO NHAPKHO { get; set; }
        public virtual SANPHAMNHAP SANPHAMNHAP { get; set; }
    }
}
