//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string SOHOADON { get; set; }
        public string MABANAN { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public string TONGMONAN { get; set; }
        public string TONGDOUONG { get; set; }
        public string CTKM { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
    
        public virtual BANAN BANAN { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
    }
}
