//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENUDOAN
    {
        public string TENMON { get; set; }
        public string DONVITINH { get; set; }
        public Nullable<decimal> GIAMON { get; set; }
    }
}
