//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYDINH
    {
        public string MAQD { get; set; }
        public string TENQD { get; set; }
        public string MANVBIPHAT { get; set; }
        public string HINHTHUCPHAT { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
