//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class XUATKHO
    {
        public string MAHDXUAT { get; set; }
        public Nullable<System.DateTime> NGAYXUAT { get; set; }
        public string MANV { get; set; }
    
        public virtual CTPX CTPX { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
